[workspace]
members = ["core_utils", "transmutador_jpg", "transmutador_png", "transmutador_webp", "transmutador_encode", "transmutador_gif", "transmutador_bmp", "transmutador_tiff", "transmutador_ico", "transmutador_tga", "transmutador_avif"]
resolver = "2"

[workspace.package]
version = "1.5.1"
edition = "2021"
license = "MIT"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
