import type { ToolDefinition } from "./types";

export const TOOLS: ToolDefinition[] = [
  {
    id: "jpg-to-png",
    slug: "jpg-to-png",
    title: "JPG → PNG",
    fromFormat: "JPG",
    toFormat: "PNG",
    module: "transmutador_jpg",
    category: "image",
    toolGroup: "jpeg-png",
    fidelity: "lossless",
    status: "active",
    acceptExtensions: [".jpg", ".jpeg"],
    outputExtension: "png",
    optionSpecs: [
      {
        kind: "slider",
        key: "compression",
        min: 1,
        max: 9,
        step: 1,
        defaultValue: 6,
        presets: [
          { label: "fast", value: 1 },
          { label: "balanced", value: 6 },
          { label: "minimal", value: 9 },
        ],
      },
    ],
  },
  {
    id: "png-to-jpg",
    slug: "png-to-jpg",
    title: "PNG → JPG",
    fromFormat: "PNG",
    toFormat: "JPG",
    module: "transmutador_png",
    category: "image",
    toolGroup: "jpeg-png",
    fidelity: "lossy",
    status: "active",
    acceptExtensions: [".png"],
    outputExtension: "jpg",
    optionSpecs: [
      {
        kind: "slider",
        key: "quality",
        min: 1,
        max: 100,
        step: 1,
        defaultValue: 85,
        presets: [
          { label: "web", value: 60 },
          { label: "balanced", value: 85 },
          { label: "high", value: 95 },
        ],
      },
      {
        kind: "color",
        key: "background",
        defaultValue: { r: 255, g: 255, b: 255 },
        swatches: [
          { label: "white", value: { r: 255, g: 255, b: 255 } },
          { label: "black", value: { r: 0, g: 0, b: 0 } },
          { label: "gray", value: { r: 128, g: 128, b: 128 } },
        ],
        allowCustom: true,
      },
    ],
  },
  {
    id: "webp-to-png",
    slug: "webp-to-png",
    title: "WebP → PNG",
    fromFormat: "WEBP",
    toFormat: "PNG",
    module: "transmutador_webp",
    category: "image",
    toolGroup: "webp",
    fidelity: "lossless",
    status: "active",
    acceptExtensions: [".webp"],
    outputExtension: "png",
    optionSpecs: [
      {
        kind: "slider",
        key: "compression",
        min: 1,
        max: 9,
        step: 1,
        defaultValue: 6,
        presets: [
          { label: "fast", value: 1 },
          { label: "balanced", value: 6 },
          { label: "minimal", value: 9 },
        ],
      },
    ],
  },
  {
    id: "webp-to-jpg",
    slug: "webp-to-jpg",
    title: "WebP → JPG",
    fromFormat: "WEBP",
    toFormat: "JPG",
    module: "transmutador_webp",
    category: "image",
    toolGroup: "webp",
    fidelity: "lossy",
    status: "active",
    acceptExtensions: [".webp"],
    outputExtension: "jpg",
    optionSpecs: [
      {
        kind: "slider",
        key: "quality",
        min: 1,
        max: 100,
        step: 1,
        defaultValue: 85,
        presets: [
          { label: "web", value: 60 },
          { label: "balanced", value: 85 },
          { label: "high", value: 95 },
        ],
      },
      {
        kind: "color",
        key: "background",
        defaultValue: { r: 255, g: 255, b: 255 },
        swatches: [
          { label: "white", value: { r: 255, g: 255, b: 255 } },
          { label: "black", value: { r: 0, g: 0, b: 0 } },
          { label: "gray", value: { r: 128, g: 128, b: 128 } },
        ],
        allowCustom: true,
      },
    ],
  },
  {
    id: "png-to-webp",
    slug: "png-to-webp",
    title: "PNG → WebP",
    fromFormat: "PNG",
    toFormat: "WEBP",
    module: "transmutador_encode",
    category: "image",
    toolGroup: "webp",
    fidelity: "lossless",
    status: "active",
    acceptExtensions: [".png"],
    outputExtension: "webp",
  },
  {
    id: "jpg-to-webp",
    slug: "jpg-to-webp",
    title: "JPEG → WebP",
    fromFormat: "JPEG",
    toFormat: "WEBP",
    module: "transmutador_encode",
    category: "image",
    toolGroup: "webp",
    fidelity: "lossless",
    status: "active",
    acceptExtensions: [".jpg", ".jpeg"],
    outputExtension: "webp",
  },
  {
    id: "gif-to-png",
    slug: "gif-to-png",
    title: "GIF → PNG",
    fromFormat: "GIF",
    toFormat: "PNG",
    module: "transmutador_gif",
    category: "image",
    toolGroup: "gif-bmp",
    fidelity: "lossless",
    status: "active",
    acceptExtensions: [".gif"],
    outputExtension: "png",
    optionSpecs: [
      {
        kind: "slider",
        key: "compression",
        min: 1,
        max: 9,
        step: 1,
        defaultValue: 6,
        presets: [
          { label: "fast", value: 1 },
          { label: "balanced", value: 6 },
          { label: "minimal", value: 9 },
        ],
      },
    ],
  },
  {
    id: "gif-to-jpg",
    slug: "gif-to-jpg",
    title: "GIF → JPG",
    fromFormat: "GIF",
    toFormat: "JPG",
    module: "transmutador_gif",
    category: "image",
    toolGroup: "gif-bmp",
    fidelity: "lossy",
    status: "active",
    acceptExtensions: [".gif"],
    outputExtension: "jpg",
    optionSpecs: [
      {
        kind: "slider",
        key: "quality",
        min: 1,
        max: 100,
        step: 1,
        defaultValue: 85,
        presets: [
          { label: "web", value: 60 },
          { label: "balanced", value: 85 },
          { label: "high", value: 95 },
        ],
      },
      {
        kind: "color",
        key: "background",
        defaultValue: { r: 255, g: 255, b: 255 },
        swatches: [
          { label: "white", value: { r: 255, g: 255, b: 255 } },
          { label: "black", value: { r: 0, g: 0, b: 0 } },
          { label: "gray", value: { r: 128, g: 128, b: 128 } },
        ],
        allowCustom: true,
      },
    ],
  },
  {
    id: "bmp-to-png",
    slug: "bmp-to-png",
    title: "BMP → PNG",
    fromFormat: "BMP",
    toFormat: "PNG",
    module: "transmutador_bmp",
    category: "image",
    toolGroup: "gif-bmp",
    fidelity: "lossless",
    status: "active",
    acceptExtensions: [".bmp"],
    outputExtension: "png",
    optionSpecs: [
      {
        kind: "slider",
        key: "compression",
        min: 1,
        max: 9,
        step: 1,
        defaultValue: 6,
        presets: [
          { label: "fast", value: 1 },
          { label: "balanced", value: 6 },
          { label: "minimal", value: 9 },
        ],
      },
    ],
  },
  {
    id: "bmp-to-jpg",
    slug: "bmp-to-jpg",
    title: "BMP → JPG",
    fromFormat: "BMP",
    toFormat: "JPG",
    module: "transmutador_bmp",
    category: "image",
    toolGroup: "gif-bmp",
    fidelity: "lossy",
    status: "active",
    acceptExtensions: [".bmp"],
    outputExtension: "jpg",
    optionSpecs: [
      {
        kind: "slider",
        key: "quality",
        min: 1,
        max: 100,
        step: 1,
        defaultValue: 85,
        presets: [
          { label: "web", value: 60 },
          { label: "balanced", value: 85 },
          { label: "high", value: 95 },
        ],
      },
      {
        kind: "color",
        key: "background",
        defaultValue: { r: 255, g: 255, b: 255 },
        swatches: [
          { label: "white", value: { r: 255, g: 255, b: 255 } },
          { label: "black", value: { r: 0, g: 0, b: 0 } },
          { label: "gray", value: { r: 128, g: 128, b: 128 } },
        ],
        allowCustom: true,
      },
    ],
  },
  {
    id: "tiff-to-png",
    slug: "tiff-to-png",
    title: "TIFF → PNG",
    fromFormat: "TIFF",
    toFormat: "PNG",
    module: "transmutador_tiff",
    category: "image",
    toolGroup: "archival",
    fidelity: "lossless",
    status: "active",
    acceptExtensions: [".tif", ".tiff"],
    outputExtension: "png",
    optionSpecs: [
      {
        kind: "slider",
        key: "compression",
        min: 1,
        max: 9,
        step: 1,
        defaultValue: 6,
        presets: [
          { label: "fast", value: 1 },
          { label: "balanced", value: 6 },
          { label: "minimal", value: 9 },
        ],
      },
    ],
  },
  {
    id: "tiff-to-jpg",
    slug: "tiff-to-jpg",
    title: "TIFF → JPG",
    fromFormat: "TIFF",
    toFormat: "JPG",
    module: "transmutador_tiff",
    category: "image",
    toolGroup: "archival",
    fidelity: "lossy",
    status: "active",
    acceptExtensions: [".tif", ".tiff"],
    outputExtension: "jpg",
    optionSpecs: [
      {
        kind: "slider",
        key: "quality",
        min: 1,
        max: 100,
        step: 1,
        defaultValue: 85,
        presets: [
          { label: "web", value: 60 },
          { label: "balanced", value: 85 },
          { label: "high", value: 95 },
        ],
      },
      {
        kind: "color",
        key: "background",
        defaultValue: { r: 255, g: 255, b: 255 },
        swatches: [
          { label: "white", value: { r: 255, g: 255, b: 255 } },
          { label: "black", value: { r: 0, g: 0, b: 0 } },
          { label: "gray", value: { r: 128, g: 128, b: 128 } },
        ],
        allowCustom: true,
      },
    ],
  },
  {
    id: "ico-to-png",
    slug: "ico-to-png",
    title: "ICO → PNG",
    fromFormat: "ICO",
    toFormat: "PNG",
    module: "transmutador_ico",
    category: "image",
    toolGroup: "icons",
    fidelity: "lossless",
    status: "active",
    acceptExtensions: [".ico", ".cur"],
    outputExtension: "png",
    optionSpecs: [
      {
        kind: "slider",
        key: "compression",
        min: 1,
        max: 9,
        step: 1,
        defaultValue: 6,
        presets: [
          { label: "fast", value: 1 },
          { label: "balanced", value: 6 },
          { label: "minimal", value: 9 },
        ],
      },
    ],
  },
  {
    id: "png-to-ico",
    slug: "png-to-ico",
    title: "PNG → ICO",
    fromFormat: "PNG",
    toFormat: "ICO",
    module: "transmutador_ico",
    category: "image",
    toolGroup: "icons",
    fidelity: "lossless",
    status: "active",
    acceptExtensions: [".png"],
    outputExtension: "ico",
    optionSpecs: [
      {
        kind: "slider",
        key: "iconSize",
        min: 256,
        max: 256,
        step: 1,
        defaultValue: 256,
        presets: [
          { label: "16", value: 16 },
          { label: "32", value: 32 },
          { label: "48", value: 48 },
          { label: "256", value: 256 },
        ],
      },
    ],
  },
  {
    id: "avif-to-jpg",
    slug: "avif-to-jpg",
    title: "AVIF → JPG",
    fromFormat: "AVIF",
    toFormat: "JPG",
    module: "transmutador_avif",
    category: "image",
    toolGroup: "avif",
    fidelity: "lossy",
    status: "active",
    acceptExtensions: [".avif"],
    outputExtension: "jpg",
    optionSpecs: [
      {
        kind: "slider",
        key: "quality",
        min: 1,
        max: 100,
        step: 1,
        defaultValue: 85,
        presets: [
          { label: "web", value: 60 },
          { label: "balanced", value: 85 },
          { label: "high", value: 95 },
        ],
      },
      {
        kind: "color",
        key: "background",
        defaultValue: { r: 255, g: 255, b: 255 },
        swatches: [
          { label: "white", value: { r: 255, g: 255, b: 255 } },
          { label: "black", value: { r: 0, g: 0, b: 0 } },
          { label: "gray", value: { r: 128, g: 128, b: 128 } },
        ],
        allowCustom: true,
      },
    ],
  },
  {
    id: "jpg-to-avif",
    slug: "jpg-to-avif",
    title: "JPEG → AVIF",
    fromFormat: "JPEG",
    toFormat: "AVIF",
    module: "transmutador_avif_encode",
    category: "image",
    toolGroup: "avif",
    fidelity: "lossy",
    status: "active",
    acceptExtensions: [".jpg", ".jpeg"],
    outputExtension: "avif",
    optionSpecs: [
      {
        kind: "slider",
        key: "quality",
        min: 1,
        max: 100,
        step: 1,
        defaultValue: 60,
        presets: [
          { label: "web", value: 45 },
          { label: "balanced", value: 60 },
          { label: "high", value: 80 },
        ],
      },
      {
        kind: "slider",
        key: "speed",
        min: 1,
        max: 10,
        step: 1,
        defaultValue: 6,
        presets: [
          { label: "quality", value: 4 },
          { label: "balanced", value: 6 },
          { label: "fast", value: 9 },
        ],
      },
    ],
  },
  {
    id: "png-to-avif",
    slug: "png-to-avif",
    title: "PNG → AVIF",
    fromFormat: "PNG",
    toFormat: "AVIF",
    module: "transmutador_avif_encode",
    category: "image",
    toolGroup: "avif",
    fidelity: "lossy",
    status: "active",
    acceptExtensions: [".png"],
    outputExtension: "avif",
    optionSpecs: [
      {
        kind: "slider",
        key: "quality",
        min: 1,
        max: 100,
        step: 1,
        defaultValue: 60,
        presets: [
          { label: "web", value: 45 },
          { label: "balanced", value: 60 },
          { label: "high", value: 80 },
        ],
      },
      {
        kind: "slider",
        key: "speed",
        min: 1,
        max: 10,
        step: 1,
        defaultValue: 6,
        presets: [
          { label: "quality", value: 4 },
          { label: "balanced", value: 6 },
          { label: "fast", value: 9 },
        ],
      },
    ],
  },
  {
    id: "avif-to-png",
    slug: "avif-to-png",
    title: "AVIF → PNG",
    fromFormat: "AVIF",
    toFormat: "PNG",
    module: "transmutador_avif",
    category: "image",
    toolGroup: "avif",
    fidelity: "lossless",
    status: "active",
    acceptExtensions: [".avif"],
    outputExtension: "png",
    optionSpecs: [
      {
        kind: "slider",
        key: "compression",
        min: 1,
        max: 9,
        step: 1,
        defaultValue: 6,
        presets: [
          { label: "fast", value: 1 },
          { label: "balanced", value: 6 },
          { label: "minimal", value: 9 },
        ],
      },
    ],
  },
  {
    id: "svg-to-png",
    slug: "svg-to-png",
    title: "SVG → PNG",
    fromFormat: "SVG",
    toFormat: "PNG",
    module: "transmutador_svg",
    category: "image",
    toolGroup: "svg",
    fidelity: "lossless",
    status: "active",
    acceptExtensions: [".svg", ".svgz"],
    outputExtension: "png",
    optionSpecs: [
      {
        kind: "slider",
        key: "outputScale",
        min: 100,
        max: 2048,
        step: 1,
        defaultValue: 100,
        presets: [
          { label: "p100", value: 100 },
          { label: "p200", value: 200 },
          { label: "px512", value: 512 },
          { label: "px1024", value: 1024 },
          { label: "px2048", value: 2048 },
        ],
      },
      {
        kind: "slider",
        key: "compression",
        min: 1,
        max: 9,
        step: 1,
        defaultValue: 6,
        presets: [
          { label: "fast", value: 1 },
          { label: "balanced", value: 6 },
          { label: "minimal", value: 9 },
        ],
      },
    ],
  },
  {
    id: "svg-to-jpg",
    slug: "svg-to-jpg",
    title: "SVG → JPG",
    fromFormat: "SVG",
    toFormat: "JPG",
    module: "transmutador_svg",
    category: "image",
    toolGroup: "svg",
    fidelity: "lossy",
    status: "active",
    acceptExtensions: [".svg", ".svgz"],
    outputExtension: "jpg",
    optionSpecs: [
      {
        kind: "slider",
        key: "outputScale",
        min: 100,
        max: 2048,
        step: 1,
        defaultValue: 100,
        presets: [
          { label: "p100", value: 100 },
          { label: "p200", value: 200 },
          { label: "px512", value: 512 },
          { label: "px1024", value: 1024 },
          { label: "px2048", value: 2048 },
        ],
      },
      {
        kind: "slider",
        key: "quality",
        min: 1,
        max: 100,
        step: 1,
        defaultValue: 85,
        presets: [
          { label: "web", value: 60 },
          { label: "balanced", value: 85 },
          { label: "high", value: 95 },
        ],
      },
      {
        kind: "color",
        key: "background",
        defaultValue: { r: 255, g: 255, b: 255 },
        swatches: [
          { label: "white", value: { r: 255, g: 255, b: 255 } },
          { label: "black", value: { r: 0, g: 0, b: 0 } },
          { label: "gray", value: { r: 128, g: 128, b: 128 } },
        ],
        allowCustom: true,
      },
    ],
  },
  {
    id: "tga-to-png",
    slug: "tga-to-png",
    title: "TGA → PNG",
    fromFormat: "TGA",
    toFormat: "PNG",
    module: "transmutador_tga",
    category: "image",
    toolGroup: "archival",
    fidelity: "lossless",
    status: "active",
    acceptExtensions: [".tga"],
    outputExtension: "png",
    optionSpecs: [
      {
        kind: "slider",
        key: "compression",
        min: 1,
        max: 9,
        step: 1,
        defaultValue: 6,
        presets: [
          { label: "fast", value: 1 },
          { label: "balanced", value: 6 },
          { label: "minimal", value: 9 },
        ],
      },
    ],
  },
  {
    id: "png-compress",
    slug: "png-compress",
    title: "PNG Compress",
    fromFormat: "PNG",
    toFormat: "PNG",
    module: "transmutador_optimize",
    category: "optimize",
    toolGroup: "jpeg-png",
    fidelity: "lossless",
    status: "active",
    acceptExtensions: [".png"],
    outputExtension: "png",
    optionSpecs: [
      {
        kind: "slider",
        key: "compression",
        min: 1,
        max: 9,
        step: 1,
        defaultValue: 9,
        presets: [
          { label: "fast", value: 1 },
          { label: "balanced", value: 6 },
          { label: "minimal", value: 9 },
        ],
      },
    ],
  },
  {
    id: "jpg-compress",
    slug: "jpg-compress",
    title: "JPEG Compress",
    fromFormat: "JPEG",
    toFormat: "JPG",
    module: "transmutador_optimize",
    category: "optimize",
    toolGroup: "jpeg-png",
    fidelity: "lossy",
    status: "active",
    acceptExtensions: [".jpg", ".jpeg"],
    outputExtension: "jpg",
    optionSpecs: [
      {
        kind: "slider",
        key: "quality",
        min: 1,
        max: 100,
        step: 1,
        defaultValue: 75,
        presets: [
          { label: "web", value: 60 },
          { label: "balanced", value: 75 },
          { label: "high", value: 90 },
        ],
      },
    ],
  },
  {
    id: "png-resize",
    slug: "png-resize",
    title: "PNG Resize",
    fromFormat: "PNG",
    toFormat: "PNG",
    module: "transmutador_optimize",
    category: "optimize",
    toolGroup: "jpeg-png",
    fidelity: "lossless",
    status: "active",
    acceptExtensions: [".png"],
    outputExtension: "png",
    optionSpecs: [
      {
        kind: "slider",
        key: "resizePercent",
        min: 1,
        max: 200,
        step: 1,
        defaultValue: 50,
        presets: [
          { label: "25%", value: 25 },
          { label: "33%", value: 33 },
          { label: "50%", value: 50 },
          { label: "66%", value: 66 },
          { label: "75%", value: 75 },
        ],
      },
    ],
  },
  {
    id: "jpg-resize",
    slug: "jpg-resize",
    title: "JPEG Resize",
    fromFormat: "JPEG",
    toFormat: "JPG",
    module: "transmutador_optimize",
    category: "optimize",
    toolGroup: "jpeg-png",
    fidelity: "lossy",
    status: "active",
    acceptExtensions: [".jpg", ".jpeg"],
    outputExtension: "jpg",
    optionSpecs: [
      {
        kind: "slider",
        key: "resizePercent",
        min: 1,
        max: 200,
        step: 1,
        defaultValue: 50,
        presets: [
          { label: "25%", value: 25 },
          { label: "33%", value: 33 },
          { label: "50%", value: 50 },
          { label: "66%", value: 66 },
          { label: "75%", value: 75 },
        ],
      },
      {
        kind: "slider",
        key: "quality",
        min: 1,
        max: 100,
        step: 1,
        defaultValue: 85,
        presets: [
          { label: "60%", value: 60 },
          { label: "75%", value: 75 },
          { label: "85%", value: 85 },
          { label: "92%", value: 92 },
        ],
      },
    ],
  },
];

export function getToolBySlug(slug: string): ToolDefinition | undefined {
  return TOOLS.find((t) => t.slug === slug);
}

export function getActiveTools(): ToolDefinition[] {
  return TOOLS.filter((t) => t.status === "active");
}

export function getSoonTools(): ToolDefinition[] {
  return TOOLS.filter((t) => t.status === "soon");
}
